<?php

namespace Database\Seeders;

use App\Models\Post;
use Illuminate\Database\Seeder;

class PostSeeder extends Seeder
{
    public function run(): void
    {
        $posts = [
            // Technology (20 posts)
            [
                'title' => 'Getting Started with Laravel 12',
                'excerpt' => 'Learn the new features and improvements in Laravel 12, including streamlined application structure and enhanced performance.',
                'content' => 'Laravel 12 brings a fresh approach to PHP development with its streamlined structure and powerful new features. The framework continues to prioritize developer experience while maintaining backward compatibility. In this guide, we will explore the key changes and how to migrate your existing applications.',
                'category' => 'Technology',
                'author_name' => 'Taylor Otwell',
                'published_at' => now()->subDays(1),
            ],
            [
                'title' => 'Building Real-Time Applications with WebSockets',
                'excerpt' => 'Discover how to implement real-time features in your web applications using WebSockets and Laravel Broadcasting.',
                'content' => 'Real-time functionality has become essential for modern web applications. From chat systems to live notifications, WebSockets provide the foundation for instant communication. This tutorial covers everything from basic setup to advanced patterns for scaling real-time features.',
                'category' => 'Technology',
                'author_name' => 'Sarah Chen',
                'published_at' => now()->subDays(3),
            ],
            [
                'title' => 'The Future of JavaScript Frameworks',
                'excerpt' => 'An analysis of emerging trends in JavaScript frameworks and what they mean for web development in 2026.',
                'content' => 'The JavaScript ecosystem continues to evolve at a rapid pace. New frameworks promise better performance, smaller bundle sizes, and improved developer experience. We examine the latest trends and predict which technologies will shape the future of frontend development.',
                'category' => 'Technology',
                'author_name' => 'Marcus Rodriguez',
                'published_at' => now()->subDays(5),
            ],
            [
                'title' => 'Understanding TypeScript Generics',
                'excerpt' => 'A comprehensive guide to mastering generics in TypeScript for type-safe and reusable code.',
                'content' => 'TypeScript generics enable you to write flexible, reusable components while maintaining strong type safety. This deep dive explores advanced generic patterns, constraints, and real-world use cases that will level up your TypeScript skills.',
                'category' => 'Technology',
                'author_name' => 'Emily Watson',
                'published_at' => now()->subDays(7),
            ],
            [
                'title' => 'Optimizing Database Queries for Performance',
                'excerpt' => 'Learn essential techniques for writing efficient database queries that scale with your application.',
                'content' => 'Database performance can make or break your application. This guide covers indexing strategies, query optimization techniques, and common pitfalls to avoid. Learn how to identify and fix slow queries before they impact your users.',
                'category' => 'Technology',
                'author_name' => 'David Park',
                'published_at' => now()->subDays(10),
            ],
            [
                'title' => 'Introduction to Docker for Developers',
                'excerpt' => 'Containerize your applications and simplify development workflows with Docker.',
                'content' => 'Docker has revolutionized how we build and deploy applications. Learn the fundamentals of containers, how to create Dockerfiles, and best practices for using Docker in development and production environments.',
                'category' => 'Technology',
                'author_name' => 'Ryan Mitchell',
                'published_at' => now()->subDays(12),
            ],
            [
                'title' => 'GraphQL vs REST: Choosing the Right API',
                'excerpt' => 'Compare GraphQL and REST to determine which API architecture fits your project needs.',
                'content' => 'Both GraphQL and REST have their strengths and trade-offs. This comprehensive comparison examines performance, flexibility, tooling, and use cases to help you make an informed decision for your next project.',
                'category' => 'Technology',
                'author_name' => 'Priya Sharma',
                'published_at' => now()->subDays(14),
            ],
            [
                'title' => 'Serverless Architecture Explained',
                'excerpt' => 'Understand serverless computing and when to use functions-as-a-service in your applications.',
                'content' => 'Serverless architecture offers scalability and cost benefits by abstracting server management. Explore AWS Lambda, Azure Functions, and best practices for building serverless applications that scale automatically.',
                'category' => 'Technology',
                'author_name' => 'Jordan Phillips',
                'published_at' => now()->subDays(16),
            ],
            [
                'title' => 'Securing Web Applications Against Common Threats',
                'excerpt' => 'Protect your applications from XSS, CSRF, SQL injection, and other security vulnerabilities.',
                'content' => 'Web security is critical in today modern threat landscape. This guide covers the OWASP Top 10 vulnerabilities, practical defense strategies, and how to implement security best practices throughout your development process.',
                'category' => 'Technology',
                'author_name' => 'Michelle Carter',
                'published_at' => now()->subDays(18),
            ],
            [
                'title' => 'Progressive Web Apps in 2026',
                'excerpt' => 'Build app-like experiences on the web with modern PWA capabilities and features.',
                'content' => 'Progressive Web Apps bridge the gap between web and native applications. Learn how to implement service workers, offline functionality, push notifications, and create installable web experiences.',
                'category' => 'Technology',
                'author_name' => 'Carlos Mendez',
                'published_at' => now()->subDays(20),
            ],
            [
                'title' => 'Microservices Architecture Patterns',
                'excerpt' => 'Design scalable systems using microservices principles and proven architectural patterns.',
                'content' => 'Microservices offer flexibility and scalability but introduce complexity. Explore service discovery, API gateways, event-driven architecture, and strategies for managing distributed systems effectively.',
                'category' => 'Technology',
                'author_name' => 'Hannah Brooks',
                'published_at' => now()->subDays(22),
            ],
            [
                'title' => 'Modern JavaScript Build Tools',
                'excerpt' => 'Navigate the landscape of build tools including Vite, esbuild, and webpack.',
                'content' => 'JavaScript build tools have evolved significantly. Compare modern options like Vite and esbuild against traditional tools, and learn which bundler best suits your project requirements and development workflow.',
                'category' => 'Technology',
                'author_name' => 'Tyler Jensen',
                'published_at' => now()->subDays(24),
            ],
            [
                'title' => 'State Management in React Applications',
                'excerpt' => 'Master state management using hooks, Context API, and external libraries like Zustand.',
                'content' => 'Effective state management is crucial for React applications. This guide covers local state, lifting state up, Context API, and when to reach for solutions like Redux, Zustand, or Jotai.',
                'category' => 'Technology',
                'author_name' => 'Samantha Lee',
                'published_at' => now()->subDays(26),
            ],
            [
                'title' => 'Performance Monitoring and APM Tools',
                'excerpt' => 'Track application performance and identify bottlenecks with modern monitoring solutions.',
                'content' => 'Application Performance Monitoring helps you understand real-world performance. Learn about New Relic, Datadog, and open-source alternatives for tracking metrics, errors, and user experience.',
                'category' => 'Technology',
                'author_name' => 'Derek Thompson',
                'published_at' => now()->subDays(28),
            ],
            [
                'title' => 'CSS Grid and Flexbox Mastery',
                'excerpt' => 'Create complex, responsive layouts using CSS Grid and Flexbox together effectively.',
                'content' => 'CSS Grid and Flexbox complement each other perfectly. This comprehensive guide teaches you when to use each layout system and how to combine them for powerful, maintainable responsive designs.',
                'category' => 'Technology',
                'author_name' => 'Natalie Wong',
                'published_at' => now()->subDays(30),
            ],
            [
                'title' => 'Building CLI Tools with Node.js',
                'excerpt' => 'Create powerful command-line interfaces using Node.js and popular libraries.',
                'content' => 'Command-line tools boost developer productivity. Learn how to build professional CLIs with Node.js, handle arguments with Commander or Yargs, and publish your tools to npm.',
                'category' => 'Technology',
                'author_name' => 'Vincent Russo',
                'published_at' => now()->subDays(32),
            ],
            [
                'title' => 'Understanding OAuth 2.0 and OpenID Connect',
                'excerpt' => 'Implement secure authentication and authorization using modern OAuth protocols.',
                'content' => 'OAuth 2.0 and OpenID Connect are standards for modern authentication. This detailed guide explains authorization flows, token management, and how to implement social login and SSO securely.',
                'category' => 'Technology',
                'author_name' => 'Patricia Hughes',
                'published_at' => now()->subDays(34),
            ],
            [
                'title' => 'NoSQL Database Design Principles',
                'excerpt' => 'Design efficient data models for MongoDB, Redis, and other NoSQL databases.',
                'content' => 'NoSQL databases require different design approaches than relational databases. Learn about document modeling, denormalization strategies, and when to choose NoSQL over traditional SQL databases.',
                'category' => 'Technology',
                'author_name' => 'Benjamin Hayes',
                'published_at' => now()->subDays(36),
            ],
            [
                'title' => 'Git Workflow Best Practices',
                'excerpt' => 'Streamline collaboration and version control with effective Git workflows and strategies.',
                'content' => 'Git is more than just version control. Explore branching strategies like Git Flow and trunk-based development, learn to write meaningful commits, and master advanced Git techniques for team collaboration.',
                'category' => 'Technology',
                'author_name' => 'Monica Rivera',
                'published_at' => now()->subDays(38),
            ],
            [
                'title' => 'Monorepo Management Strategies',
                'excerpt' => 'Organize multiple projects in a single repository using modern monorepo tools.',
                'content' => 'Monorepos simplify dependency management and code sharing. Learn about tools like Turborepo and Nx, workspace organization, and strategies for scaling monorepos across large teams.',
                'category' => 'Technology',
                'author_name' => 'Xavier Brooks',
                'published_at' => now()->subDays(40),
            ],

            // Design (20 posts)
            [
                'title' => 'Principles of Modern UI Design',
                'excerpt' => 'Explore the fundamental principles that create intuitive and beautiful user interfaces.',
                'content' => 'Great UI design is built on timeless principles: hierarchy, contrast, alignment, and consistency. This article breaks down each principle with practical examples and shows how to apply them to create interfaces that users love.',
                'category' => 'Design',
                'author_name' => 'Olivia Martinez',
                'published_at' => now()->subDays(2),
            ],
            [
                'title' => 'Creating Accessible Web Experiences',
                'excerpt' => 'A practical guide to building websites that everyone can use, regardless of ability.',
                'content' => 'Accessibility is not optional—it is a fundamental aspect of good design. Learn how to implement ARIA labels, keyboard navigation, and color contrast ratios that ensure your applications are usable by everyone.',
                'category' => 'Design',
                'author_name' => 'James Foster',
                'published_at' => now()->subDays(4),
            ],
            [
                'title' => 'The Power of Whitespace in Design',
                'excerpt' => 'How strategic use of negative space can transform your designs from cluttered to elegant.',
                'content' => 'Whitespace is one of the most powerful yet underutilized tools in a designer toolkit. It creates breathing room, establishes hierarchy, and guides the user eye. Learn how to use whitespace effectively to create clean, professional designs.',
                'category' => 'Design',
                'author_name' => 'Sophie Anderson',
                'published_at' => now()->subDays(6),
            ],
            [
                'title' => 'Color Theory for Web Designers',
                'excerpt' => 'Master the art of color selection and create harmonious palettes that enhance user experience.',
                'content' => 'Understanding color theory is essential for creating visually appealing interfaces. This guide covers color psychology, palette generation, and practical tips for choosing colors that work together and support your design goals.',
                'category' => 'Design',
                'author_name' => 'Alex Thompson',
                'published_at' => now()->subDays(8),
            ],
            [
                'title' => 'Responsive Design Best Practices',
                'excerpt' => 'Build layouts that look great on every device with these responsive design techniques.',
                'content' => 'With users accessing websites from countless devices, responsive design is no longer optional. Learn mobile-first approaches, breakpoint strategies, and fluid typography techniques that ensure your designs work everywhere.',
                'category' => 'Design',
                'author_name' => 'Rachel Kim',
                'published_at' => now()->subDays(11),
            ],
            [
                'title' => 'Typography for Interfaces',
                'excerpt' => 'Choose and pair fonts that enhance readability and strengthen your brand identity.',
                'content' => 'Typography shapes how users perceive and interact with your interface. Learn about font pairing, type scale, line height, and accessibility considerations for creating readable, beautiful text hierarchies.',
                'category' => 'Design',
                'author_name' => 'Isabella Torres',
                'published_at' => now()->subDays(13),
            ],
            [
                'title' => 'Micro-Interactions That Delight Users',
                'excerpt' => 'Add polish to your interfaces with thoughtful animations and micro-interactions.',
                'content' => 'Small animations make big differences in user experience. Discover how to design button states, loading indicators, and transitions that provide feedback and create delightful moments.',
                'category' => 'Design',
                'author_name' => 'Nathan Ford',
                'published_at' => now()->subDays(15),
            ],
            [
                'title' => 'Design Systems from Scratch',
                'excerpt' => 'Build consistent, scalable design systems that grow with your product and team.',
                'content' => 'Design systems ensure consistency across products and speed up development. Learn how to audit your design, define tokens, create component libraries, and document patterns that scale.',
                'category' => 'Design',
                'author_name' => 'Chloe Bennett',
                'published_at' => now()->subDays(17),
            ],
            [
                'title' => 'Mobile-First Design Philosophy',
                'excerpt' => 'Start with mobile constraints to create better experiences across all devices.',
                'content' => 'Mobile-first design forces you to prioritize content and features. This approach leads to cleaner, more focused interfaces that scale up gracefully to larger screens and complex interactions.',
                'category' => 'Design',
                'author_name' => 'Gabriel Silva',
                'published_at' => now()->subDays(19),
            ],
            [
                'title' => 'The Psychology of UI Elements',
                'excerpt' => 'Understand how users perceive and interact with common interface patterns.',
                'content' => 'User interface design is rooted in psychology. Explore how mental models, affordances, and familiarity influence design decisions and create intuitive experiences that feel natural to users.',
                'category' => 'Design',
                'author_name' => 'Vanessa Morgan',
                'published_at' => now()->subDays(21),
            ],
            [
                'title' => 'Dark Mode Design Considerations',
                'excerpt' => 'Design dark themes that reduce eye strain and look stunning.',
                'content' => 'Dark mode is now expected in modern applications. Learn about color adjustments, contrast ratios, and design decisions that make dark themes comfortable and accessible for extended use.',
                'category' => 'Design',
                'author_name' => 'Julian Reed',
                'published_at' => now()->subDays(23),
            ],
            [
                'title' => 'Icon Design Principles',
                'excerpt' => 'Create clear, recognizable icons that enhance your interface navigation.',
                'content' => 'Icons communicate meaning instantly when designed well. This guide covers grid systems, optical sizing, consistency, and best practices for creating or customizing icon sets for your projects.',
                'category' => 'Design',
                'author_name' => 'Lily Chambers',
                'published_at' => now()->subDays(25),
            ],
            [
                'title' => 'Form Design for Better Conversions',
                'excerpt' => 'Design forms that users actually want to complete with smart UX patterns.',
                'content' => 'Forms are critical conversion points. Learn about field grouping, inline validation, progressive disclosure, and other techniques that reduce friction and improve form completion rates.',
                'category' => 'Design',
                'author_name' => 'Oscar Diaz',
                'published_at' => now()->subDays(27),
            ],
            [
                'title' => 'Designing for Multiple Platforms',
                'excerpt' => 'Maintain brand consistency while respecting platform conventions across web, iOS, and Android.',
                'content' => 'Each platform has unique design patterns and user expectations. Learn how to adapt your designs for web, iOS, and Android while maintaining a cohesive brand experience.',
                'category' => 'Design',
                'author_name' => 'Aurora Collins',
                'published_at' => now()->subDays(29),
            ],
            [
                'title' => 'Information Architecture Fundamentals',
                'excerpt' => 'Organize content logically to help users find what they need quickly.',
                'content' => 'Good information architecture is invisible but essential. Master card sorting, site maps, navigation patterns, and content hierarchy to create intuitive structures that scale.',
                'category' => 'Design',
                'author_name' => 'Felix Wright',
                'published_at' => now()->subDays(31),
            ],
            [
                'title' => 'Button Design Best Practices',
                'excerpt' => 'Design buttons that clearly communicate actions and hierarchy.',
                'content' => 'Buttons are fundamental interface elements. Learn about sizing, spacing, color, states, and labeling that make buttons accessible, clickable, and clearly communicative of their purpose.',
                'category' => 'Design',
                'author_name' => 'Maya Patel',
                'published_at' => now()->subDays(33),
            ],
            [
                'title' => 'Error States and Empty States',
                'excerpt' => 'Design helpful messages for when things go wrong or content is missing.',
                'content' => 'Error and empty states are opportunities to guide users. Create messages that explain what happened, why, and what users can do next with clarity and personality.',
                'category' => 'Design',
                'author_name' => 'Ethan Cooper',
                'published_at' => now()->subDays(35),
            ],
            [
                'title' => 'Loading States and Skeletons',
                'excerpt' => 'Keep users engaged during loading with smart placeholder patterns.',
                'content' => 'Loading states set performance expectations. Explore skeleton screens, progressive loading, and animation patterns that reduce perceived wait time and maintain user engagement.',
                'category' => 'Design',
                'author_name' => 'Zara Mitchell',
                'published_at' => now()->subDays(37),
            ],
            [
                'title' => 'Component Library Organization',
                'excerpt' => 'Structure your design components for maximum reusability and discoverability.',
                'content' => 'Well-organized component libraries accelerate design and development. Learn naming conventions, variant structures, and documentation patterns that make components easy to find and use.',
                'category' => 'Design',
                'author_name' => 'Logan Barnes',
                'published_at' => now()->subDays(39),
            ],
            [
                'title' => 'Gesture Design for Touch Interfaces',
                'excerpt' => 'Create intuitive touch interactions for mobile and tablet applications.',
                'content' => 'Touch interfaces require different interaction patterns than desktop. Learn about swipe, pinch, long-press, and other gestures that feel natural and discoverable on touch devices.',
                'category' => 'Design',
                'author_name' => 'Yolanda Pierce',
                'published_at' => now()->subDays(41),
            ],

            // Business (20 posts)
            [
                'title' => 'Building a Successful SaaS Product',
                'excerpt' => 'Key strategies for launching and growing a profitable software-as-a-service business.',
                'content' => 'The SaaS market is competitive, but the right approach can lead to sustainable growth. This article covers pricing strategies, customer acquisition, retention tactics, and metrics that matter for SaaS success.',
                'category' => 'Business',
                'author_name' => 'Michael Chang',
                'published_at' => now()->subDays(2),
            ],
            [
                'title' => 'Remote Team Management in 2026',
                'excerpt' => 'Effective strategies for leading distributed teams and maintaining productivity.',
                'content' => 'Remote work is here to stay, and managing distributed teams requires new approaches. Learn how to build trust, facilitate communication, and create a culture of accountability across time zones.',
                'category' => 'Business',
                'author_name' => 'Jennifer Lee',
                'published_at' => now()->subDays(5),
            ],
            [
                'title' => 'Understanding Customer Lifetime Value',
                'excerpt' => 'Calculate and optimize CLV to make better business decisions and improve profitability.',
                'content' => 'Customer Lifetime Value is one of the most important metrics for sustainable business growth. This guide shows you how to calculate CLV, identify your most valuable customers, and strategies to increase customer value over time.',
                'category' => 'Business',
                'author_name' => 'Robert Johnson',
                'published_at' => now()->subDays(9),
            ],
            [
                'title' => 'Content Marketing That Converts',
                'excerpt' => 'Create content strategies that attract your ideal customers and drive real business results.',
                'content' => 'Content marketing is more than blogging—it is about creating valuable resources that solve real problems. Learn how to identify topics that resonate, optimize for search engines, and measure the ROI of your content efforts.',
                'category' => 'Business',
                'author_name' => 'Amanda White',
                'published_at' => now()->subDays(12),
            ],
            [
                'title' => 'Pricing Strategies for Digital Products',
                'excerpt' => 'Find the optimal pricing model for your digital product and maximize revenue.',
                'content' => 'Pricing can make or break a digital product. Explore different pricing models including freemium, tiered pricing, and usage-based billing. Learn how to test pricing strategies and find the sweet spot for your market.',
                'category' => 'Business',
                'author_name' => 'Daniel Brown',
                'published_at' => now()->subDays(15),
            ],
            [
                'title' => 'Fundraising for Startups in 2026',
                'excerpt' => 'Navigate the funding landscape and secure investment for your startup.',
                'content' => 'Raising capital requires strategy and preparation. Learn about funding stages, investor expectations, pitch deck essentials, and alternative funding sources beyond traditional venture capital.',
                'category' => 'Business',
                'author_name' => 'Victoria Chen',
                'published_at' => now()->subDays(18),
            ],
            [
                'title' => 'Building a Strong Company Culture',
                'excerpt' => 'Create values and practices that attract talent and drive success.',
                'content' => 'Company culture is not ping pong tables—it is the values and behaviors that define how work gets done. Learn how to define, communicate, and maintain culture as your team grows.',
                'category' => 'Business',
                'author_name' => 'Marcus Williams',
                'published_at' => now()->subDays(20),
            ],
            [
                'title' => 'Product-Market Fit: Finding It and Keeping It',
                'excerpt' => 'Identify and validate product-market fit to ensure sustainable growth.',
                'content' => 'Product-market fit is the foundation of successful products. This guide covers how to measure fit, recognize the signs, and adjust your product strategy based on real user feedback.',
                'category' => 'Business',
                'author_name' => 'Natasha Kumar',
                'published_at' => now()->subDays(22),
            ],
            [
                'title' => 'Email Marketing That Gets Results',
                'excerpt' => 'Build email campaigns that engage subscribers and drive conversions.',
                'content' => 'Email remains one of the highest ROI marketing channels. Learn segmentation strategies, subject line best practices, and automation workflows that turn subscribers into customers.',
                'category' => 'Business',
                'author_name' => 'Steven Ross',
                'published_at' => now()->subDays(24),
            ],
            [
                'title' => 'Analytics That Actually Matter',
                'excerpt' => 'Focus on metrics that drive business decisions instead of vanity numbers.',
                'content' => 'Not all metrics are created equal. Learn to distinguish between vanity metrics and actionable insights, set up proper tracking, and use data to make informed business decisions.',
                'category' => 'Business',
                'author_name' => 'Alicia Grant',
                'published_at' => now()->subDays(26),
            ],
            [
                'title' => 'Customer Support as a Growth Channel',
                'excerpt' => 'Turn support interactions into opportunities for retention and expansion.',
                'content' => 'Great support creates loyal customers and word-of-mouth growth. Explore support strategies, tools, and metrics that transform customer service from cost center to competitive advantage.',
                'category' => 'Business',
                'author_name' => 'Brandon Scott',
                'published_at' => now()->subDays(28),
            ],
            [
                'title' => 'Building Strategic Partnerships',
                'excerpt' => 'Identify and nurture partnerships that accelerate business growth.',
                'content' => 'Strategic partnerships extend your reach and capabilities. Learn how to identify potential partners, structure win-win agreements, and manage relationships for long-term mutual benefit.',
                'category' => 'Business',
                'author_name' => 'Diana Peterson',
                'published_at' => now()->subDays(30),
            ],
            [
                'title' => 'Reducing Customer Churn',
                'excerpt' => 'Identify churn signals early and implement retention strategies that work.',
                'content' => 'Acquiring customers is expensive—keeping them is more profitable. Learn to identify at-risk customers, implement proactive retention tactics, and build products people do not want to leave.',
                'category' => 'Business',
                'author_name' => 'Gregory Hall',
                'published_at' => now()->subDays(32),
            ],
            [
                'title' => 'The Lean Startup Methodology',
                'excerpt' => 'Build products iteratively using validated learning and rapid experimentation.',
                'content' => 'The Lean Startup approach minimizes waste and maximizes learning. Master the build-measure-learn loop, MVP development, and pivot strategies to find product-market fit faster.',
                'category' => 'Business',
                'author_name' => 'Pamela Martinez',
                'published_at' => now()->subDays(34),
            ],
            [
                'title' => 'Scaling Your Business Operations',
                'excerpt' => 'Build processes and systems that support growth without breaking.',
                'content' => 'What works at ten customers breaks at a hundred. Learn how to document processes, implement automation, and build operational foundations that scale with your business.',
                'category' => 'Business',
                'author_name' => 'Raymond Bell',
                'published_at' => now()->subDays(36),
            ],
            [
                'title' => 'Competitive Analysis Frameworks',
                'excerpt' => 'Understand your market position and identify opportunities for differentiation.',
                'content' => 'Competitive analysis informs strategy and positioning. Learn frameworks for analyzing competitors, identifying gaps, and carving out unique value propositions in crowded markets.',
                'category' => 'Business',
                'author_name' => 'Stephanie Moore',
                'published_at' => now()->subDays(38),
            ],
            [
                'title' => 'User Onboarding That Sticks',
                'excerpt' => 'Design first experiences that activate users and demonstrate value quickly.',
                'content' => 'First impressions matter. Create onboarding flows that guide users to their aha moment, reduce time-to-value, and set the foundation for long-term engagement.',
                'category' => 'Business',
                'author_name' => 'Kenneth Young',
                'published_at' => now()->subDays(40),
            ],
            [
                'title' => 'Building a Personal Brand',
                'excerpt' => 'Establish thought leadership and grow your professional influence.',
                'content' => 'Personal branding opens doors and creates opportunities. Learn how to identify your unique value, create consistent content, and build an audience that trusts your expertise.',
                'category' => 'Business',
                'author_name' => 'Melissa Adams',
                'published_at' => now()->subDays(42),
            ],
            [
                'title' => 'Negotiation Skills for Founders',
                'excerpt' => 'Master the art of negotiation for better deals and partnerships.',
                'content' => 'Negotiation is a critical founder skill. Learn preparation tactics, communication strategies, and frameworks for reaching agreements that benefit all parties involved.',
                'category' => 'Business',
                'author_name' => 'Timothy Clark',
                'published_at' => now()->subDays(44),
            ],
            [
                'title' => 'Community Building for Products',
                'excerpt' => 'Foster engaged user communities that drive growth and retention.',
                'content' => 'Strong communities create loyal users and organic growth. Learn how to seed discussions, recognize contributors, and build platforms where users help and inspire each other.',
                'category' => 'Business',
                'author_name' => 'Yvonne Sanders',
                'published_at' => now()->subDays(46),
            ],

            // Lifestyle (20 posts)
            [
                'title' => 'Work-Life Balance for Developers',
                'excerpt' => 'Practical tips for maintaining health and happiness while building your career in tech.',
                'content' => 'The tech industry can be demanding, but burnout is not inevitable. Learn strategies for setting boundaries, managing stress, and creating a sustainable work rhythm that supports both your career and personal life.',
                'category' => 'Lifestyle',
                'author_name' => 'Lisa Wang',
                'published_at' => now()->subDays(3),
            ],
            [
                'title' => 'The Digital Minimalism Movement',
                'excerpt' => 'Reclaim your focus and time by intentionally reducing digital distractions.',
                'content' => 'Our devices promise connection but often deliver distraction. Digital minimalism offers a framework for being more intentional about technology use. Discover how to declutter your digital life and focus on what truly matters.',
                'category' => 'Lifestyle',
                'author_name' => 'Tom Harrison',
                'published_at' => now()->subDays(6),
            ],
            [
                'title' => 'Building Better Morning Routines',
                'excerpt' => 'Start your day with purpose using these evidence-based morning routine strategies.',
                'content' => 'How you start your day sets the tone for everything that follows. This article explores the science behind effective morning routines and provides practical templates you can customize to fit your life and goals.',
                'category' => 'Lifestyle',
                'author_name' => 'Maria Santos',
                'published_at' => now()->subDays(8),
            ],
            [
                'title' => 'The Art of Deep Work',
                'excerpt' => 'Master the ability to focus without distraction and produce your best work.',
                'content' => 'In an age of constant interruption, the ability to do deep work is increasingly rare and valuable. Learn techniques for creating focus, managing attention, and structuring your day to maximize productive output.',
                'category' => 'Lifestyle',
                'author_name' => 'Kevin O\'Brien',
                'published_at' => now()->subDays(13),
            ],
            [
                'title' => 'Sustainable Living in the Digital Age',
                'excerpt' => 'Small changes that reduce your environmental impact while embracing modern technology.',
                'content' => 'Technology and sustainability can coexist. Explore practical ways to reduce your carbon footprint, from energy-efficient devices to mindful consumption habits that benefit both the planet and your well-being.',
                'category' => 'Lifestyle',
                'author_name' => 'Grace Miller',
                'published_at' => now()->subDays(16),
            ],
            [
                'title' => 'Mindfulness for Busy Professionals',
                'excerpt' => 'Incorporate mindfulness practices into your daily routine to reduce stress.',
                'content' => 'Mindfulness does not require hours of meditation. Learn practical techniques for staying present during meetings, commutes, and everyday activities to reduce stress and increase clarity.',
                'category' => 'Lifestyle',
                'author_name' => 'Jasmine Reynolds',
                'published_at' => now()->subDays(19),
            ],
            [
                'title' => 'Home Office Setup Essentials',
                'excerpt' => 'Create a productive workspace that supports health and focus.',
                'content' => 'Your workspace affects productivity and well-being. This guide covers ergonomic furniture, lighting, organization systems, and equipment that create an effective home office environment.',
                'category' => 'Lifestyle',
                'author_name' => 'Sebastian Price',
                'published_at' => now()->subDays(21),
            ],
            [
                'title' => 'Financial Planning for Freelancers',
                'excerpt' => 'Manage irregular income and build financial stability as a freelancer.',
                'content' => 'Freelancing brings financial uncertainty. Learn budgeting strategies for variable income, tax planning, emergency fund building, and retirement savings tailored for independent workers.',
                'category' => 'Lifestyle',
                'author_name' => 'Angela Torres',
                'published_at' => now()->subDays(23),
            ],
            [
                'title' => 'The Power of Saying No',
                'excerpt' => 'Protect your time and energy by setting clear boundaries.',
                'content' => 'Every yes is a no to something else. Learn how to decline requests gracefully, set boundaries that stick, and prioritize commitments that align with your goals and values.',
                'category' => 'Lifestyle',
                'author_name' => 'Derek Campbell',
                'published_at' => now()->subDays(25),
            ],
            [
                'title' => 'Continuous Learning Strategies',
                'excerpt' => 'Stay relevant and grow your skills in a rapidly changing world.',
                'content' => 'Lifelong learning is essential in tech. Discover strategies for choosing what to learn, creating learning habits, and balancing skill development with your existing commitments.',
                'category' => 'Lifestyle',
                'author_name' => 'Bianca Lopez',
                'published_at' => now()->subDays(27),
            ],
            [
                'title' => 'Exercise Routines for Desk Workers',
                'excerpt' => 'Combat sedentary work with movement routines that fit your schedule.',
                'content' => 'Sitting all day takes a toll on health. Explore desk-friendly exercises, stretching routines, and movement strategies that counteract the effects of prolonged sitting.',
                'category' => 'Lifestyle',
                'author_name' => 'Maxwell Porter',
                'published_at' => now()->subDays(29),
            ],
            [
                'title' => 'Meal Prep for Busy Schedules',
                'excerpt' => 'Save time and eat healthier with strategic meal planning and preparation.',
                'content' => 'Meal prep removes daily decision fatigue around food. Learn batch cooking techniques, storage strategies, and simple recipes that make healthy eating convenient.',
                'category' => 'Lifestyle',
                'author_name' => 'Ruby Henderson',
                'published_at' => now()->subDays(31),
            ],
            [
                'title' => 'Sleep Optimization for Developers',
                'excerpt' => 'Improve sleep quality to boost performance and overall health.',
                'content' => 'Quality sleep enhances cognitive function and productivity. Discover science-backed strategies for better sleep hygiene, managing screen time, and creating evening routines that promote rest.',
                'category' => 'Lifestyle',
                'author_name' => 'Adrian Foster',
                'published_at' => now()->subDays(33),
            ],
            [
                'title' => 'Building Meaningful Connections',
                'excerpt' => 'Cultivate relationships that enrich your personal and professional life.',
                'content' => 'Strong relationships contribute to happiness and success. Learn how to network authentically, maintain friendships despite busy schedules, and build a supportive community.',
                'category' => 'Lifestyle',
                'author_name' => 'Penelope Shaw',
                'published_at' => now()->subDays(35),
            ],
            [
                'title' => 'Managing Decision Fatigue',
                'excerpt' => 'Reduce mental load by streamlining decisions and creating helpful defaults.',
                'content' => 'Every decision drains mental energy. Learn strategies for reducing daily choices through routines, automation, and systems that preserve cognitive resources for what matters most.',
                'category' => 'Lifestyle',
                'author_name' => 'Curtis Graham',
                'published_at' => now()->subDays(37),
            ],
            [
                'title' => 'Creative Hobbies for Tech Workers',
                'excerpt' => 'Balance analytical work with creative pursuits that refresh your mind.',
                'content' => 'Creative hobbies provide mental balance and new perspectives. Explore activities from music to woodworking that complement tech work and foster creativity outside of code.',
                'category' => 'Lifestyle',
                'author_name' => 'Fiona Marshall',
                'published_at' => now()->subDays(39),
            ],
            [
                'title' => 'Time Management Without Burnout',
                'excerpt' => 'Manage your time effectively while maintaining energy and enthusiasm.',
                'content' => 'Productivity is not about doing more—it is about doing what matters. Learn time management techniques that respect your energy levels and create sustainable work patterns.',
                'category' => 'Lifestyle',
                'author_name' => 'Preston Ward',
                'published_at' => now()->subDays(41),
            ],
            [
                'title' => 'Travel Tips for Remote Workers',
                'excerpt' => 'Maintain productivity while exploring new places as a digital nomad.',
                'content' => 'Remote work enables location independence. Learn how to choose workation destinations, manage time zones, find reliable wifi, and balance work with exploration.',
                'category' => 'Lifestyle',
                'author_name' => 'Savannah Knight',
                'published_at' => now()->subDays(43),
            ],
            [
                'title' => 'Reading Habits That Stick',
                'excerpt' => 'Build a consistent reading practice and get more from books.',
                'content' => 'Reading expands knowledge and perspective. Discover strategies for reading more consistently, choosing impactful books, and retaining what you read through note-taking and reflection.',
                'category' => 'Lifestyle',
                'author_name' => 'Wesley Brooks',
                'published_at' => now()->subDays(45),
            ],
            [
                'title' => 'Managing Stress in High-Pressure Roles',
                'excerpt' => 'Build resilience and cope with workplace stress effectively.',
                'content' => 'High-pressure roles demand stress management skills. Learn techniques for staying calm under pressure, processing difficult emotions, and maintaining perspective when stakes are high.',
                'category' => 'Lifestyle',
                'author_name' => 'Zachary Hayes',
                'published_at' => now()->subDays(47),
            ],

            // Tutorial (20 posts)
            [
                'title' => 'Build a Todo App with Livewire',
                'excerpt' => 'Step-by-step tutorial for creating a dynamic todo application using Laravel Livewire.',
                'content' => 'Learn Livewire fundamentals by building a practical todo application. This hands-on tutorial covers component creation, real-time updates, validation, and persistence—all without writing JavaScript.',
                'category' => 'Tutorial',
                'author_name' => 'Chris Evans',
                'published_at' => now()->subDays(4),
            ],
            [
                'title' => 'Mastering Tailwind CSS Utilities',
                'excerpt' => 'A comprehensive guide to Tailwind responsive design, dark mode, and custom configurations.',
                'content' => 'Tailwind CSS offers incredible flexibility through utility classes. This tutorial dives deep into responsive modifiers, state variants, and customization options that let you build exactly the design you envision.',
                'category' => 'Tutorial',
                'author_name' => 'Nina Patel',
                'published_at' => now()->subDays(7),
            ],
            [
                'title' => 'API Development with Laravel Sanctum',
                'excerpt' => 'Learn to build secure REST APIs with token-based authentication using Laravel Sanctum.',
                'content' => 'Laravel Sanctum makes API authentication simple and secure. This tutorial walks through creating protected endpoints, issuing tokens, and handling permissions for both SPAs and mobile applications.',
                'category' => 'Tutorial',
                'author_name' => 'Andrew Cooper',
                'published_at' => now()->subDays(10),
            ],
            [
                'title' => 'Testing Laravel Applications with Pest',
                'excerpt' => 'Write elegant, readable tests using Pest PHP and improve your application reliability.',
                'content' => 'Pest PHP brings a fresh approach to testing with its expressive syntax and powerful features. Learn how to write unit tests, feature tests, and use datasets to ensure your Laravel applications work flawlessly.',
                'category' => 'Tutorial',
                'author_name' => 'Sophia Turner',
                'published_at' => now()->subDays(14),
            ],
            [
                'title' => 'Creating Custom Artisan Commands',
                'excerpt' => 'Automate repetitive tasks by building your own Laravel Artisan commands.',
                'content' => 'Artisan commands are powerful tools for automation. This tutorial teaches you how to create custom commands, handle arguments and options, and integrate them into your development workflow.',
                'category' => 'Tutorial',
                'author_name' => 'Lucas Garcia',
                'published_at' => now()->subDays(17),
            ],
            [
                'title' => 'Build a Real-Time Chat with Pusher',
                'excerpt' => 'Create a live chat application using Laravel Broadcasting and Pusher.',
                'content' => 'Real-time chat demonstrates broadcasting fundamentals. Follow this step-by-step tutorial to build a working chat system with presence channels, typing indicators, and message persistence.',
                'category' => 'Tutorial',
                'author_name' => 'Gabriella West',
                'published_at' => now()->subDays(19),
            ],
            [
                'title' => 'File Upload with Drag and Drop',
                'excerpt' => 'Implement intuitive file uploads with drag-and-drop using Alpine.js and Livewire.',
                'content' => 'File uploads do not have to be clunky. Learn to build a drag-and-drop upload interface with progress tracking, validation, and previews using Alpine.js and Livewire.',
                'category' => 'Tutorial',
                'author_name' => 'Harrison Cole',
                'published_at' => now()->subDays(21),
            ],
            [
                'title' => 'Implementing Dark Mode Toggle',
                'excerpt' => 'Add dark mode to your application with Tailwind CSS and localStorage.',
                'content' => 'Users expect dark mode options. This tutorial walks through implementing a dark mode toggle using Tailwind CSS classes, Alpine.js for state management, and localStorage for persistence.',
                'category' => 'Tutorial',
                'author_name' => 'Iris Montgomery',
                'published_at' => now()->subDays(23),
            ],
            [
                'title' => 'Search with Autocomplete',
                'excerpt' => 'Build responsive search with autocomplete suggestions and keyboard navigation.',
                'content' => 'Great search experiences guide users to results quickly. Create an autocomplete search feature with debouncing, keyboard navigation, and smart result highlighting.',
                'category' => 'Tutorial',
                'author_name' => 'Jackson Riley',
                'published_at' => now()->subDays(25),
            ],
            [
                'title' => 'Data Tables with Sorting and Filtering',
                'excerpt' => 'Create feature-rich data tables with pagination, sorting, and search.',
                'content' => 'Data tables are common UI components. Build a complete table solution with column sorting, multi-column filtering, pagination, and bulk actions using Livewire.',
                'category' => 'Tutorial',
                'author_name' => 'Kimberly Fisher',
                'published_at' => now()->subDays(27),
            ],
            [
                'title' => 'Building a Kanban Board',
                'excerpt' => 'Create a drag-and-drop kanban board for task management.',
                'content' => 'Kanban boards provide visual task management. Learn to build a draggable kanban interface with column customization, card details, and real-time updates using Livewire Sortable.',
                'category' => 'Tutorial',
                'author_name' => 'Lorenzo Diaz',
                'published_at' => now()->subDays(29),
            ],
            [
                'title' => 'Image Cropper with Preview',
                'excerpt' => 'Allow users to crop and adjust images before upload.',
                'content' => 'Image cropping improves uploaded content quality. Build an image cropper with aspect ratio controls, zoom, and real-time preview before final upload and processing.',
                'category' => 'Tutorial',
                'author_name' => 'Meredith Blake',
                'published_at' => now()->subDays(31),
            ],
            [
                'title' => 'Multi-Step Form Wizard',
                'excerpt' => 'Guide users through complex forms with step-by-step wizards.',
                'content' => 'Long forms overwhelm users. Create a multi-step wizard with progress indication, validation per step, and the ability to navigate back and forth while preserving data.',
                'category' => 'Tutorial',
                'author_name' => 'Nathaniel Price',
                'published_at' => now()->subDays(33),
            ],
            [
                'title' => 'Notification System with Toasts',
                'excerpt' => 'Display temporary notifications using toast messages and animations.',
                'content' => 'Toast notifications provide non-intrusive feedback. Build a notification system with stacking, auto-dismiss, different types (success, error, info), and smooth animations.',
                'category' => 'Tutorial',
                'author_name' => 'Ophelia Sanders',
                'published_at' => now()->subDays(35),
            ],
            [
                'title' => 'Calendar Event Scheduler',
                'excerpt' => 'Create an interactive calendar for scheduling and viewing events.',
                'content' => 'Build a calendar component that displays events, allows date selection, and integrates with your backend to create and manage scheduled items across month, week, and day views.',
                'category' => 'Tutorial',
                'author_name' => 'Quentin Hayes',
                'published_at' => now()->subDays(37),
            ],
            [
                'title' => 'Implementing Infinite Scroll',
                'excerpt' => 'Load content progressively as users scroll down the page.',
                'content' => 'Infinite scroll improves perceived performance. Learn to implement intersection observers, manage state, and handle edge cases for smooth infinite scrolling experiences.',
                'category' => 'Tutorial',
                'author_name' => 'Rebecca Ward',
                'published_at' => now()->subDays(39),
            ],
            [
                'title' => 'Tag Input Component',
                'excerpt' => 'Build a flexible tag input for categories, labels, and multi-select.',
                'content' => 'Tag inputs enable flexible categorization. Create a tag component with autocomplete, validation, duplicate prevention, and visual feedback for adding and removing tags.',
                'category' => 'Tutorial',
                'author_name' => 'Samuel Griffin',
                'published_at' => now()->subDays(41),
            ],
            [
                'title' => 'Modal Dialogs and Overlays',
                'excerpt' => 'Create accessible modal dialogs with proper focus management.',
                'content' => 'Modals require careful implementation for accessibility. Build modal components with focus trapping, escape key handling, backdrop clicks, and screen reader support.',
                'category' => 'Tutorial',
                'author_name' => 'Tiffany Coleman',
                'published_at' => now()->subDays(43),
            ],
            [
                'title' => 'Password Strength Indicator',
                'excerpt' => 'Provide real-time feedback on password strength during registration.',
                'content' => 'Help users create secure passwords with visual strength indicators. Implement real-time validation that checks length, character variety, and common password patterns.',
                'category' => 'Tutorial',
                'author_name' => 'Ulysses Morgan',
                'published_at' => now()->subDays(45),
            ],
            [
                'title' => 'Building a Command Palette',
                'excerpt' => 'Create keyboard-driven navigation with a command palette interface.',
                'content' => 'Command palettes enable power users to navigate quickly. Build a searchable command interface with keyboard shortcuts, fuzzy search, and action execution inspired by tools like VS Code.',
                'category' => 'Tutorial',
                'author_name' => 'Violet Anderson',
                'published_at' => now()->subDays(47),
            ],
        ];

        // Clear existing posts
        Post::query()->delete();

        // Create the curated posts
        foreach ($posts as $post) {
            Post::create($post);
        }
    }
}
